%% compare concatenated touchstone files generated by the ads project and the new algorithm

%% loads the concatenated touchstone file generated by the ads project 
addpath('C:\Users\younger\Documents\MATLAB\_develop\_chasim\impulse_response_oct2012');
addpath('C:\Users\younger\Documents\MATLAB\_develop\_chasim\SYZ_conversions');

s4ppath = 'C:\Users\younger\Documents\MATLAB\_develop\_chasim\Qlogic_Cetus_wrk';
ads_s4pname = 'spara1.s4p';
ads_s4pfile = fullfile(s4ppath, ads_s4pname);
ads_s4pstruct = tsnpimporti(ads_s4pfile);

hs = sparameters('spara1.s4p');
figure;
rfplot(hs)
